name: Python application

on:
  push:
    branches: [ "main" ] # ou o nome da sua branch principal
  pull_request:
    branches: [ "main" ] # ou o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # para a build se houver erros de sintaxe do Python ou nomes indefinidos
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # o exit-zero trata todos os erros como avisos. O editor do GitHub tem 127 caracteres de largura
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
