# Nome do seu workflow
name: Python com Conda e requirements.txt

# Gatilhos (quando vai rodar)
on:
  push:
    branches: [ "main" ] # Mude para sua branch principal se for outra
  pull_request:
    branches: [ "main" ] # Mude aqui também, se precisar

# Jobs
jobs:
  build:
    # Máquina que vai rodar
    runs-on: ubuntu-latest

    # Passos
    steps:
      # 1. Copia o código do repositório
      - name: Clonar o repositório
        uses: actions/checkout@v4

      # 2. Configura o Conda
      - name: Setup do Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.10'

      # 3. Cria o ambiente e instala as dependências via pip
      - name: Instalar dependências
        run: |
          conda create --name meu-ambiente python=3.10 -y
          eval "$(conda shell.bash hook)"
          conda activate meu-ambiente
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Roda o Flake8 para verificar o código
      - name: Rodar o Linter (Flake8)
        run: |
          eval "$(conda shell.bash hook)"
          conda activate meu-ambiente
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
